<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
<groupId>io.github.hiwepy</groupId><artifactId>shiro-saml-extension</artifactId><version>1.0.x.20260630-SNAPSHOT</version><packaging>jar</packaging>
<repositories><repository><id>spring-release</id><url>https://build.shibboleth.net/nexus/content/repositories/releases/</url></repository></repositories>
<properties><project.build.sourceEncoding>UTF-8</project.build.sourceEncoding><java.version>1.8</java.version><opensaml.version>3.4.2</opensaml.version><java-support.version>7.3.0</java-support.version></properties>
<dependencies>
<dependency><groupId>org.projectlombok</groupId><artifactId>lombok</artifactId><version>1.18.30</version><scope>provided</scope></dependency>
<dependency><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId><version>1.7.32</version></dependency>

<dependency><groupId>org.apache.shiro</groupId><artifactId>shiro-core</artifactId><version>2.2.1</version></dependency><dependency><groupId>org.apache.shiro</groupId><artifactId>shiro-web</artifactId><version>2.2.0</version></dependency><dependency><groupId>io.github.hiwepy</groupId><artifactId>shiro-biz</artifactId><version>2.0.0.RELEASE</version></dependency><dependency><groupId>org.opensaml</groupId><artifactId>opensaml-core</artifactId><version>${opensaml.version}</version></dependency><dependency><groupId>net.shibboleth.utilities</groupId><artifactId>java-support</artifactId><version>${java-support.version}</version></dependency><dependency><groupId>javax.servlet</groupId><artifactId>javax.servlet-api</artifactId><version>4.0.1</version><scope>provided</scope></dependency></dependencies>
<build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><version>3.8.1</version><configuration><source>1.8</source><target>1.8</target></configuration></plugin></plugins></build>
</project>
