<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
    <parent><groupId>io.github.easy4j</groupId><artifactId>shiro-saml</artifactId><version>1.0.x.20260630-SNAPSHOT</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>shiro-saml-core</artifactId><name>${project.groupId}:${project.artifactId}</name>
    <dependencies>
        <dependency><groupId>org.apache.shiro</groupId><artifactId>shiro-core</artifactId></dependency>
        <dependency><groupId>org.opensaml</groupId><artifactId>opensaml-core</artifactId></dependency>
        <dependency><groupId>net.shibboleth.utilities</groupId><artifactId>java-support</artifactId></dependency>
    </dependencies>
</project>
